import dash
from dash import dcc, html
from dash.dependencies import Input, Output, State
import dash_bootstrap_components as dbc
from components.sidebar import create_sidebar  # Sidebar importée depuis components
from pages import home, prediction, map, contexte  # Importation des pages

external_stylesheets = [
    {
        "href": (
            "https://fonts.googleapis.com/css2?"
            "family=Lato:wght@400;700&display=swap"
        ),
        "rel": "stylesheet",
    }]

fields = ['Etiquette_DPE',
    'Type_bâtiment',
    'Coût_chauffage',
    'Année_construction',
    'Surface_habitable_immeuble',
    'Emission_GES_5_usages',
    'Coût_chauffage_dépensier',
    'Conso_5_usages_é_finale',
    'Adresse_brute',
    'Code_postal_(BAN)',
    'Identifiant__BAN',
    'Date_réception_DPE',
    'Adresse_(BAN)',
    'Qualité_isolation_enveloppe',
    'Surface_habitable_logement',
    'Coût_auxiliaires',
    'Type_installation_chauffage_n°1',
    'Type_installation_chauffage',
    'Conso_5_usages/m²_é_finale',
    'Coût_refroidissement',
    'Type_énergie_n°1',
    'Coût_ECS',
    'Coût_total_5_usages',
    'Coût_éclairage'
    ]

# fields = [
#     "Conso_chauffage_dépensier_é_finale",
#     "Volume_stockage_générateur_ECS_n°1",
#     "Conso_é_finale_installation_ECS",
#     "Nom__commune_(BAN)",
#     "Emission_GES_chauffage",
#     "Conso_ECS_é_finale_énergie_n°2",
#     "Conso_ECS_é_finale_énergie_n°1",
#     "Besoin_refroidissement",
#     "Conso_chauffage_dépensier_installation_chauffage_n°1",
#     "Coût_total_5_usages",
#     "Configuration_installation_chauffage_n°1",
#     "Conso_é_finale_dépensier_installation_ECS",
#     "Configuration_installation_ECS",
#     "Type_installation_chauffage_n°1",
#     "Surface_chauffée_installation_chauffage_n°1",
#     "Coordonnée_cartographique_X_(BAN)",
#     "Nombre_niveau_logement",
#     "Apports_internes_saison_froid",
#     "Déperditions_murs",
#     "Conso_5_usages_par_m²_é_primaire",
#     "Coût_refroidissement",
#     "Ubat_W/m²_K",
#     "Usage_générateur_ECS_n°1",
#     "Coût_ECS_dépensier",
#     "Emission_GES_auxiliaires",
#     "Emission_GES_5_usages_par_m²",
#     "Emission_GES_éclairage",
#     "Apports_solaires_saison_froid",
#     "Conso_ECS_dépensier_é_finale",
#     "Catégorie_ENR",
#     "Adresse_(BAN)",
#     "Date_visite_diagnostiqueur",
#     "N°_étage_appartement",
#     "Type_énergie_générateur_ECS_n°1",
#     "Coût_ECS",
#     "Surface_habitable_desservie_par_installation_ECS",
#     "Coût_éclairage",
#     "Date_établissement_DPE",
#     "Coût_total_5_usages_énergie_n°2",
#     "Type_générateur_ECS_n°1",
#     "Coût_total_5_usages_énergie_n°1",
#     "Description_installation_chauffage_n°1",
#     "N°_voie_(BAN)",
#     "Besoin_ECS",
#     "N°DPE",
#     "Conso_refroidissement_é_finale",
#     "Logement_traversant_(0/1)",
#     "Conso_chauffage_é_primaire",
#     "Adresse_brute",
#     "Conso_éclairage_é_primaire",
#     "Qualité_isolation_menuiseries",
#     "Qualité_isolation_murs",
#     "Emission_GES_5_usages_énergie_n°1",
#     "Type_émetteur_installation_chauffage_n°1",
#     "Emission_GES_5_usages_énergie_n°2",
#     "Statut_géocodage",
#     "Emission_GES_ECS_énergie_n°2",
#     "Classe_inertie_bâtiment",
#     "Emission_GES_ECS_énergie_n°1",
#     "Modèle_DPE",
#     "Description_générateur_chauffage_n°1_installation_n°1",
#     "Description_générateur_ECS_n°1",
#     "Production_électricité_PV_(kWhep/an)",
#     "Conso_5_usages_é_finale",
#     "Nombre_logements_desservis_par_installation_ECS",
#     "N°_département_(BAN)",
#     "Conso_refroidissement_é_primaire",
#     "Méthode_application_DPE",
#     "N°_région_(BAN)",
#     "Surface_habitable_logement",
#     "Code_postal_(brut)",
#     "Deperditions_planchers_bas",
#     "Coordonnée_cartographique_Y_(BAN)",
#     "_rand",
#     "Période_construction",
#     "Emission_GES_ECS_dépensier",
#     "Emission_GES_chauffage_énergie_n°2",
#     "Emission_GES_chauffage_énergie_n°1",
#     "Conso_é_finale_dépensier_générateur_ECS_n°1",
#     "Emission_GES_refroidissement",
#     "Classe_altitude",
#     "Indicateur_confort_été",
#     "Description_installation_ECS",
#     "Qualité_isolation_plancher_haut_comble_aménagé",
#     "Emission_GES_ECS",
#     "Type_énergie_n°1",
#     "Type_énergie_n°2",
#     "Coût_ECS_énergie_n°2",
#     "Date_réception_DPE",
#     "Coût_ECS_énergie_n°1",
#     "Type_installation_ECS",
#     "Conso_ECS_é_finale",
#     "Présence_brasseur_air_(0/1)",
#     "Emission_GES_5_usages",
#     "Code_postal_(BAN)",
#     "Conso_éclairage_é_finale",
#     "Coût_refroidissement_dépensier",
#     "Date_fin_validité_DPE",
#     "Deperditions_planchers_hauts",
#     "Emission_GES_refroidissement_dépensier",
#     "Type_bâtiment",
#     "Apports_solaires_saison_chauffe",
#     "Conso_chauffage_générateur_n°1_installation_n°1",
#     "Coût_chauffage",
#     "Déperditions_renouvellement_air",
#     "Protection_solaire_exterieure_(0/1)",
#     "Déperditions_portes",
#     "_geopoint",
#     "Conso_chauffage_installation_chauffage_n°1",
#     "Conso_ECS_dépensier_é_primaire",
#     "Zone_climatique_",
#     "Conso_refroidissement_dépensier_é_finale",
#     "Usage_générateur_n°1_installation_n°1",
#     "Version_DPE",
#     "Deperditions_baies_vitrées",
#     "Conso_chauffage_dépensier_générateur_n°1_installation_n°1",
#     "Type_énergie_générateur_n°1_installation_n°1",
#     "Déperditions_ponts_thermiques",
#     "Type_énergie_principale_chauffage",
#     "Inertie_lourde_(0/1)",
#     "Qualité_isolation_enveloppe",
#     "Emission_GES_chauffage_dépensier",
#     "Besoin_chauffage",
#     "Isolation_toiture_(0/1)",
#     "Conso_ECS_é_primaire",
#     "Etiquette_GES",
#     "Conso_5_usages_é_finale_énergie_n°1",
#     "Conso_5_usages_é_finale_énergie_n°2",
#     "Complément_d'adresse_bâtiment",
#     "Conso_auxiliaires_é_primaire",
#     "Conso_auxiliaires_é_finale",
#     "Conso_é_finale_générateur_ECS_n°1",
#     "Conso_chauffage_é_finale",
#     "Coût_chauffage_dépensier",
#     "Etiquette_DPE",
#     "Conso_refroidissement_dépensier_é_primaire",
#     "Besoin_refroidissement_dépensier",
#     "Type_générateur_n°1_installation_n°1",
#     "Coût_chauffage_énergie_n°1",
#     "_i",
#     "Coût_chauffage_énergie_n°2",
#     "Qualité_isolation_plancher_bas",
#     "Apports_internes_saison_chauffe_",
#     "Conso_5_usages/m²_é_finale",
#     "Hauteur_sous-plafond",
#     "Identifiant__BAN",
#     "Coût_auxiliaires",
#     "Nom__rue_(BAN)",
#     "Conso_chauffage_dépensier_é_primaire",
#     "Code_INSEE_(BAN)",
#     "Score_BAN",
#     "Deperditions_enveloppe",
#     "Type_énergie_principale_ECS",
#     "Conso_5_usages_é_primaire",
#     "Conso_chauffage_é_finale_énergie_n°2",
#     "Conso_chauffage_é_finale_énergie_n°1",
#     "_score",
#     "_id",
#     "Conso_ECS_é_finale_énergie_n°3",
#     "Conso_chauffage_générateur_n°2_installation_n°1",
#     "Coût_total_5_usages_énergie_n°3",
#     "Conso_chauffage_dépensier_générateur_n°2_installation_n°1",
#     "Emission_GES_5_usages_énergie_n°3",
#     "Emission_GES_ECS_énergie_n°3",
#     "Emission_GES_chauffage_énergie_n°3",
#     "Type_énergie_n°3",
#     "Coût_ECS_énergie_n°3",
#     "Description_générateur_chauffage_n°2_installation_n°1",
#     "Type_générateur_n°2_installation_n°1",
#     "Conso_5_usages_é_finale_énergie_n°3",
#     "Usage_générateur_n°2_installation_n°1",
#     "Type_énergie_générateur_n°2_installation_n°1",
#     "Coût_chauffage_énergie_n°3",
#     "Conso_chauffage_é_finale_énergie_n°3",
#     "N°_DPE_remplacé",
#     "Qualité_isolation_plancher_haut_comble_perdu",
#     "Type_installation_ECS_(général)",
#     "Complément_d'adresse_logement",
#     "Nombre_appartement",
#     "Type_installation_chauffage",
#     "Conso_chauffage_dépensier_installation_chauffage_n°2",
#     "Configuration_installation_chauffage_n°2",
#     "Type_installation_chauffage_n°2",
#     "Surface_chauffée_installation_chauffage_n°2",
#     "Description_installation_chauffage_n°2"
# ]